### ISSUE TITLE
Audio stream to wave file

### ISSUE THREAD

**Issue by J0n8s** [doe300/OHMComm#12]
Implement simple audio output to wave file streamer
-http://www3.nd.edu/~dthain/courses/cse20211/fall2013/wavfile/

**Comment by Kaayy-J** [comment]
@J0n8s 
If you are stuck, you should move to your next issue #18.

**Comment by doe300** [comment]
The wavfile-code above only supports mono, that's why it never did sound properly.

**Comment by J0n8s** [comment]
Problem was that the "simple audio output to wave file streamer" from http://www3.nd.edu/~dthain/courses/cse20211/fall2013/wavfile/ writes a textfile not a binary file to disk, in order to write a binary file we need to change the options from "w+" to "wb+" Line 52 in File http://www3.nd.edu/~dthain/courses/cse20211/fall2013/wavfile/wavfile.c
Mono - Stero can be switched with the Parameter in Line 45 header.num_channels = 2;
