### ISSUE TITLE
RTPBuffer

### ISSUE THREAD

**Issue by doe300** [doe300/OHMComm#14]
Implement RTP jitter buffer, supporting multithreaded read/write.
More precisly: Support one write-thread and one thread reading packages.
The buffer should return some kind of silent-package if its contents are empty.
Provide an interface of public methods for both threads

**Comment by Kaayy-J** [comment]
Add mutex for winOS, see RTAudioWrapper.cpp

**Comment by Kaayy-J** [comment]
@doe300 I'm not sure whether std::mutex is supported correctly on windows. But it seems to be it is compilable with windows. I suggest to implement a linux solution first, before making any changes related for windows support.

**Comment by doe300** [comment]
Now works under Linux with RTPListener-thread and synchronized RTPBuffer, with almost no processor-usage!

@Kaayy-J, @J0n8s please test under windows. In particular the thread-synchronization, because I'm not sure, whether windows uses mutex correctly
