### ISSUE TITLE
Refactoring, Documentation

### ISSUE THREAD

**Issue by Kaayy-J** [doe300/OHMComm#20]
Since there has been major changes in the project structure it is necessary to write a documentation. Also refactoring might be useful.

**Comment by Kaayy-J** [comment]
Code review of RTPBuffer.cpp and RTPBuffer.h

**Comment by Kaayy-J** [comment]
I would suggest to use doxygen as documentation tool.
http://www.doxygen.org/index.html

**Comment by doe300** [comment]
For doxygen (or any other tool) to work, you guys need to write/modify documentation-comments if you add any new method/class or rewrite an existing!

**Comment by Kaayy-J** [comment]
Thats worth the effort.

**Comment by doe300** [comment]
Added wiki-page on how to document code: https://github.com/doe300/OHMComm/wiki/Documentation-Style

**Comment by doe300** [comment]
TODO:
Write/Improve documentation for all public classes

**Comment by doe300** [comment]
Tested generating documentation via doxygen, which adds a doc-folder with ~10MB in size. So I'd suggest we stick to documenting our code and let the html-documentation off (can locally be generated if needed)
