### ISSUE TITLE
Profiler

### ISSUE THREAD

**Issue by doe300** [doe300/OHMComm#25]
Create Profiler for callback-method:
- [x] measure execution times for every AudioProcessor
- [x] make optional, so it doesn't affect performance if disabled

**Comment by doe300** [comment]
@Kaayy-J, some things you should improve:
- [x] use at least microsecond precision
- [x] please do rewrite the Profiler to move it out of AudioHandler (e.g. create own class and call its methods from AudioHandler or wrap the AudioProcessors in decorators)

**Comment by doe300** [comment]
~~@Kaayy-J, audio-output lags the moment, the profile is printed to the console~~ Fixed

**Comment by Kaayy-J** [comment]
@doe300 Thanks for the enhancement
