### ISSUE TITLE
Test transmission over LAN / WAN

### ISSUE THREAD

**Issue by doe300** [doe300/OHMComm#26]
Status of tests:
- [x] transmission over LAN: good quality, tested by @Kaayy-J 
- [x] transmission over WLAN: good quality~~, but package loss, program crashes,~~ tested by @J0n8s 
- [x] transmission over WWW: good quality, tested by @J0n8s and @Kaayy-J

**Comment by Kaayy-J** [comment]
Not working on my computer. 
I do not received any packages on both computers.
Even If I send packages to myself over Network-IP-Address I dont receive any. 
Works only with localhost.

**Comment by doe300** [comment]
Currently, the program can't run on any other than localhost:
1. OHMComm hard-codes "127.0.0.1" as local address, so it only can listen on loopback, I think?
2. As of your last change, there is no way to configure a local port manually

**Comment by Kaayy-J** [comment]
Works fine over LAN.

**Comment by doe300** [comment]
Test over internet worked partially, @Kaayy-J received packages but could not hear me, I could hear him quite good. Probably doesn't work due to task #42.

**Comment by doe300** [comment]
Test over internet with myself (extern IP of my router) worked without problems.
Some notes for testing: Make sure, your network can handle the bandwidth in down- and upload!

**Comment by doe300** [comment]
We need to run another test via WWW using passive configuration (and perhaps the alternative buffer-implementation).

**Comment by J0n8s** [comment]
Tested transmission over WLAN with the newest version: IPv6 works, good quality, some buffer underflows (should be normal), no crashes. Looks good :)

**Comment by J0n8s** [comment]
Tested transmission over WWW with @Kaayy-J : transmission with int-16 and float-32 worked great, the sound quality was very good. No noticeable difference between int-16 and float-32 on 48000khz, on 16000khz the quality was a bit poorer (as expected) but not very much.
Statistic from the last test run:

```
Recorded 4696320 audio-frames (16171.9 fps)
Played 18785280 bytes (17.92 MB) of audio-data (63.17 KB/s)
Played 4696320 audio-frames (16171.9 fps)

+++ Network statistics +++
Sent 4892 packages (16.8457 per second)
Sent 1272757 bytes (1.21 MB) in total (4.28 KB/s)
Sent 1214053 bytes (1.16 MB) of audio-data (4.08 KB/s)
Sent 58704 bytes (57.33 KB) of RTP-header (202.15 B/s)
Sent 58704 of 1214053 bytes as overhead (4.83%)
Received 4884 packages (16.8182 per second)
Received 1271156 bytes (1.21 MB) in total (4.27 KB/s)
Received 1212548 bytes (1.16 MB) of audio-data (4.08 KB/s)
Received 58608 bytes (57.23 KB) of RTP-header (201.82 B/s)
Received 58608 of 1212548 bytes as overhead (4.83%)
Lost 0 RTP-packages (0 packages per second)

+++ Buffer statistics +++
Maximum buffer usage was 3 of 256 packages (1.17%)

+++ Compression statistics +++
Compressed 17.92 MB of audio-data into 1.16 MB (93.53% compression)
Decompressed 17.92 MB of audio-data out of 1.16 MB (93.54% decompression)

+++ AudioProcessor statistics +++

Opus-Codec
        Processing audio-input took 8044592 microseconds in total (822.219 microseconds per call)
        Processing audio-output took  2609851 microseconds in total (266.747 microseconds per call)

RTP-Processor
        Processing audio-input took 102812 microseconds in total (10.5082 microseconds per call)
        Processing audio-output took  39285 microseconds in total (4.01523 microseconds per call)
```

**Comment by doe300** [comment]
Everything is done here. Release v0.5 will come as soon as I have my internet connection back working.
