### ISSUE TITLE
Extend processor-chaining

### ISSUE THREAD

**Issue by Kaayy-J** [doe300/OHMComm#32]
- [x] Remove global AudioConfiguration
- [x] Allow for processors for modifying (returning) the number of buffered bytes to be provided for next processor
- [x] move maximum buffer bytes to StreamData
- [x] Add methods to AudioProcessors to provide supported audio-configuration (esp. format, samplerate, bufferframes)
- [x] Allow for AudioHandler to use accepted values from AudioProcessors
- [x] add AudioConfiguration as parameter to AudioHandler#configure()

**Comment by doe300** [comment]
mostly implemtend, still TODO:
- add method to AudioProcessor to provide supported number of buffered frames
- Allow for AudioHandler to use accepted values from AudioProcessors

**Comment by doe300** [comment]
To be added:
- [x] RTPPackageHandler needs to be extended to store actual package size. This will be set (on the receiving side) by RTPBuffer and used in ProcessorRTP to set the newly implemented bufferSize
- [x] ProcessorRTP must ~~initialize buffer in configure and~~ use correct buffer size!
