### ISSUE TITLE
Solve problem with different audio-formats on computers

### ISSUE THREAD

**Issue by Kaayy-J** [doe300/OHMComm#42]
Currently both computers need to have the same audio configuration (sample-rate, format, samples per package).
We need to find a way to either
- allow for varying input and output configuration
  or
- agree on a common configuration.

Possible solutions:
- use custom payload-format with the audio-configuration as parameter
- write SIP stack to agree on configuration

See #35

**Comment by doe300** [comment]
As of now, audio-format and sample-rate can be set manually.
With the completion of passive configuration, there will also be a way to circumvent this problem automatically.

**Comment by doe300** [comment]
By using the passive configuration-mode, the audio-configuration will be synced between the two devices.
