### ISSUE TITLE
Fixed Error on Shutdown

### ISSUE THREAD

**Issue by Kaayy-J** [doe300/OHMComm#47]
Application crashes on exit.

**Comment by Kaayy-J** [comment]
Fixed.

**Comment by doe300** [comment]
We need to test this with communication over different devices

**Comment by Kaayy-J** [comment]
Why is the test with different devices necessary? Do you expect different behaviour?
Why is the issue marked as bug?

**Comment by doe300** [comment]
Because currently, when the RTPListener receives an BYE-packet, it shuts down, but the recording/sending and playback on that program still runs. So we either need to shut the other program down completely or at least make sure, it doesn't throw any errors.
You marked it as bug:)

**Comment by Kaayy-J** [comment]
I havn't tested it with two computers, but the behavior I expect needs attention.

Computer 1                 | Computer2
audioObject.started     | audioObject.started
rtpListener.started       | rtpListener.started

Computer2 shuts down:

Computer 1                 | Computer2
audioObject.started     | audioObject.stopped
rtpListener.stopped     | rtpListener.stopped

On Computer1 the audioObject is still running, while its rtpListener has stopped because of the RTCP-Bye-Package.

**Comment by Kaayy-J** [comment]
A possible solution would be to enable communication between audioObject (RTAudioThread) and RTPListener (own Thread).
