### ISSUE TITLE
Make use of RTCP protocol

### ISSUE THREAD

**Issue by doe300** [doe300/OHMComm#48]
We already have a working but not used RTCP-implementation.
- [x] Find some way to distinguish RTP-packages from RTCP-packages (I belive there is a bit pattern to separate them).
- [x] Use the RTCP BYE-message to fix the problem addressed in #47 in an more clear matter.
- [x] Use the RTCP APP-defined package to transmit the available/used stream-configuration. This could be used to aggree to the same configuration as of #42 .
- [x] Implement usage of SDES: load from file and send on start-up, receiving side prints info to console
- [x] Implement Sender and Reception Reports. Finished as of e69409e0a46a7daa1f5f48a920d5dbb7062b8d2c

**Comment by Kaayy-J** [comment]
Does not work on real enviroment (test with J0n8s). Following errors received:
Output Buffer underflow
Invalid package received

**Comment by doe300** [comment]
@Kaayy-J, do you have any more specific error-message or log-file to attach?

**Comment by Kaayy-J** [comment]
Sorry, I didnt activate logging. So there is no file.

**Comment by doe300** [comment]
Passive configuration works!
