### ISSUE TITLE
Add a way to stop audio-threads

### ISSUE THREAD

**Issue by doe300** [doe300/OHMComm#49]
We need some mechanism to stop the AudioHandler and its thread other than exiting the main-method.
- [x] Make the AudioHandler accessible, so the stop-method can be called
- [x] Make sure all other threads/objects are shut down correctly
- [x] Preferably create an universal accessible way to stop all threads, close network, print statistics.

This would fix #47

**Comment by Kaayy-J** [comment]
I do not have a solution yet, but consider the main thread, which is waiting for input.
We need a communication between 3 Threads.

**Comment by doe300** [comment]
Commit f0c7b45c6c7a27d2d0dbae6e61717dd8929ba3a5 introduces a OHMComm-object which can stop audio and receiving thread programmatically.

Remaining TODO:
- ~~Stop the audio-thread when the listener-thread received a GOODBYE-package~~ Done
- Stopping via the RTPListener needs to be tested on multiple devices

**Comment by doe300** [comment]
Tested via 2 pcs, it works!
Shutting down the one client triggers the other client to shut down too.
