### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by Kaayy-J** [doe300/OHMComm#5]
~~Write useful UnitTests.~~
We need to write extensive tests for:
- ~~RTAudioWrapper (as far as possible)~~
- [x] AudioProcessors (as far as possible)
- [x] NetworkWrappers
- [x] RTCPPackageHander
- [x] RTPPackageHander
- [x] RTPBuffer
- [x] UserInput
- [x] ConfigurationModes

**Comment by doe300** [comment]
I just moved all test-classes to own folder (./test/) to not clutter the production-code. I also moved the test-cases out of OhmComm into own executables, @Kaayy-J, @J0n8s please test under windows, if CMake is configured correctly

**Comment by doe300** [comment]
We need to write extensive tests until the next release for:
- [ ] RTAudioWrapper
- [ ] AudioProcessors
- [ ] NetworkWrappers
- [ ] RT(C)PPackageHander
- [ ] RTPBuffer
- [ ] UserInput
