### ISSUE TITLE
Fix RT(C)P Header

### ISSUE THREAD

**Issue by doe300** [doe300/OHMComm#61]
The memory layout of C++ bit-fields is implementation-defined. Therefore our implementations of the RTPHeader, RTCPHeader, -Extensions and all types of RTCP package-types are wrong.

Alas, we need to rewrite them to explicitly set the correct bits. Since we have to rewrite all fields to getter/setter for manipulating/reading the specified bits, we can use this to complete the rewrite to network byte-order.

Un-/Correctness can be tested via https://www.wireshark.org/

**Comment by Kaayy-J** [comment]
Lets discuss about this on the next meeting.

**Comment by doe300** [comment]
Fixed as of commit 33f469c92e87eca3deb5f6facfdf41c95bc3f7f6
