### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by doe300** [doe300/OHMComm#67]
~~Liste der Themen zum Verteilen und Abhaken~~
- Einleitung (Themenstellung, Ziele)
- Werkzeuge(CMake,GitHub)
- Architektur
- RtAudio
- Opus
- RTP
- Buffer
- RTCP ??
- Konfigurations-Modi
- Statistiken ??
- Fazit(Probleme und Lösungen??), Ausblick (auf Version 0.8+??)

@J0n8s, @Kaayy-J ich würde empfehlen, die Arbeit auf Basis von Version 0.7 zu schreiben, da 0.8+ zu große Änderungen haben werden

**Comment by J0n8s** [comment]
0.7 als Basis klingt gut
Themen hinzugefügt

**Comment by Kaayy-J** [comment]
Bezüglich Themenauswahl und -zuordnung können wir uns am Vortrag richten.

@doe300 Du könntest dich kürzer formulieren bezüglich RTCP und den Konfigurations-Modi, da diese nicht explizit verlangt waren.

Wann war nochmal Abgabe?

**Comment by doe300** [comment]
Deswegen haben die Themen ja auch ein paar ??
Abgabe ist spätestens 14.02.2016 -> 7 Wochen -> Wir sollten mal anfangen

**Comment by Kaayy-J** [comment]
Es wird etwas problematisch beim Verteilen der Schreibblöcke, aber im allgemeinen würde ich so eine Struktur von der Arbeit erwarten:

Die Arbeit muss formal sein - so ähnlich wie eine Abschlussarbeit, aber nicht so streng.

Einleitung

> Wer ist Auftraggeber? Wer sind die Beteiligten?
> Was ist das Ziel? Wie ist der Kenntnisstand zu Beginn?
> Wie war die Vorgehensweise (Vorgehensmodell)? (Iterativ? Da nach jedem Meeting stufenweise Verfeinerung?).
> Aufbau des Berichts (Aus Gründen der Lesbarkeit und um ein einfaches Nachschlagen zu ermöglichen ist der Bericht klassisch nach dem Basismodell (Wasserfallmodell?) aufgebaut.)

Anforderungsanalyse

> Dieser Abschnitt beantwortet die Frage was das System leisten soll? 
> 
> Welche Funktionale und Nicht-Funktionale Anforderungen gibt es?
> Welche Daten fallen an?
> 
> > Wie werden Daten gespeichert und abgerufen? (Datenhaushalt)
> > Gibt es Kennzahlen? (Richtwerte?)
> > Zum Beispiel für die Verarbeitungsgeschwindigkeit? 
> > Nachdem die oberen Punkte abgearbeitet sind, müssen Lösungsalternativen betrachtet werden. Gab es Alternativen für OHMComm ? (Zum Glück gab es keine, sonst hätten wir kein Projekt)
> > Eventuell ein Lasten- und Pflichtenheft

Entwurf

> Dieser Abschnitt beantworet die Frage wie das System aufgebaut und gestaltet sein sein?
> 
> Wie wird das Projekt verwaltet? (Github, Whatsapp, Meetings)
> Welche Werkzeuge werden eingesetzt? (CMake, IDEs, Github)
> 
> Die Hardware- und Softwarearchitektur müssen geklärt werden.
> 
> > Hardware ist sehr vielfältig -> Architektur setzt auf Betriebssystemebene auf
> > Welche Betriebssysteme werden eingesetzt?
> > Welche Softwarekomponenten gibt es? (RTAudio, CPPTest, Opus)
> > Wie können diese optimal in die Software integriert werden?
> > 
> > Wie können die Anforderungen umsetzt werden? Warum wurde welche Entscheidung getroffen?
> > Einzelnen Softwarekomponenten müssen genannt und spezifiziert werden.

Implementierung

> Alle Komponenten
> ..
> ..

Prototypen

> Filerecorder
> Voice-over-IP Konsolenanwendung

Projektabschluss und Ausblick

> Wurden alle Ziele erreicht?
> Reflektionsphase (Haben wir toll gemacht - Wir sind die Besten)
> Erweiterungen und mögliche Beispielanwendungen
> Persönliches Fazit

**Comment by doe300** [comment]
Damit kommen wir auf jeden Fall auf unsere 80 Seiten.
@Kaayy-J, würdest du des so mal in LaTeX als Menü eintippen und dann können wir ja die entstandenen Kapitel und Abschnitte aufteilen

**Comment by Kaayy-J** [comment]
Okay erledigt. Ihr dürfte gerne ergänzen und umstrukturieren.

**Comment by doe300** [comment]
Aufteilung Teile:
- Einleitung (@Kaayy-J)
  - Ziel
  - Aufbau des Berichts
- Anforderungsanalyse (@Kaayy-J)
  - Funktionale und Nicht-Funktionale Anforderungen
- Entwurf
  - Projektverwaltung und Werkzeuge  (@J0n8s)
    - Github mit Issues, Treffen
    - CMake, IDEs + Plattformen
    - Testumgebung (CPPTest, Travis)
  - Build Prozess  (@J0n8s)
    - Vereinheitlicht via CMake
    - Build-Prozess unter Linux (@doe300)
    - Build unter Windows
  - Softwarearchitektur
    - Konfiguration und Verwendung (Interaktiv, Bibliothek) (@doe300)
    - AudioHandler (Hardware-Schnittstelle) (@Kaayy-J)
    - Verarbeitungskette, Prozessoren (Profiling, z.B. Kompression, Packen, ...) (@Kaayy-J)
    - Austauschbarkeit und Instanziierung der Komponenten (Factory-Pattern) (@Kaayy-J)
    - RTP-Protokoll (@doe300)
      - RTCP-Protokoll
    - RTP-Buffer (@doe300)
    - Netzwerk (@doe300)
  - Konkrete Softwarekomponenten (Alternativen und Begründung)  (@J0n8s)
    - RTAudio
    - Opus
  - Statistiken (@doe300)
    - Aufbau, Ausgabe in Datei
    - Bedeutung der Werte
- Implementierung
  - (erwähnenswerte Punkte aus Entwurf)
- Prototypische Voice-over-IP Konsolenanwendungen
  - Ziel der Anwendung
  - Steuerung
  - Anwendungen ordnungsgemäß beenden (Probleme, Beenden aller Threads)
- Fazit und Ausblick
  - Projektergebnis
  - Anwendungsmöglichkeiten
  - Erweiterungsmöglichkeiten (@doe300)

**Comment by Kaayy-J** [comment]
Ich würde einen Termin für kommende Woche (1.2 - 7.2)  mit folgenden Inhalt vorschlagen:
1. Aktueller Stand von jedem
2. Korrekturlesen
3. Verteilen der restlichen Schreibblöcke

Ich würde gerne ab dem 8.2 oder Anfang dieser Woche fertig sein.

**Comment by doe300** [comment]
Könnten wir schon machen. Ihr solltet aber auch erstmal euren Stand hochladen, damit wir auf einen gemeinsamen Nenner kommen.

**Comment by Kaayy-J** [comment]
Ich bringe mein Änderung online, wenn ich mind. 5 Seiten hab (heute Abend oder morgen irgendwann).

**Comment by Kaayy-J** [comment]
Wir müssen ein paar Konventionen erstellen für einen einheitlichen Stil.
- Methodennamen immer mit Klammern angeben
- Parameter der Methoden sind optional - können auch weggelassen werden
- Klassen, Methoden und Variablen werden immer hervorgehoben mit dem Befehl "texttt"
- Section in Absätzen oder in Subsections einteilen (Um zu große Absätze zu verhindern)
- Glossar erstellen (Damit die Begriffe eindeutig und überall konsistent verwendet werden wie z.B. RTPBuffer = Jitterbuffer = Jitter-Buffer)

**Comment by Kaayy-J** [comment]
@doe300 Schau dir bitte die TODOs an. Ich bin erst heute Abend wieder in Whatsapp erreichbar.

**Comment by doe300** [comment]
Kann auch erst heute Abend wieder dran arbeiten, aber ich schau se mir dann an
