### ISSUE TITLE
Stream from/to file

### ISSUE THREAD

**Issue by doe300** [doe300/OHMComm#8]
Write a NetworkWrapper
- Writes samples from rtaudio-buffer to audio file
- Reads samples from file and writes it into rtaudio-buffer
- Filenames are configurable (see AudioProcessor#configure())

P.S. Maybe NetworkWrapper is not such a good name, rename it to something like IOWrapper or AudioIO, ...

**Comment by Kaayy-J** [comment]
This has been implemented already.  But as a part of the reorganisation it was removed again.

This issue has been re-asigned @J0n8s as modified issue. See #12 for more information.
